# 04 — PR Collection & LLM-Only Risk Assessment

This notebook implements the first half of the change risk experiment:

1. **Fetch recent merged PRs** from all 13 Django ecosystem repos via the GitHub API
2. **Extract diffs** and map changed entities (modules, classes, functions) to graph node IDs
3. **LLM-only risk assessment** — prompt GPT-4o with just the PR diff for structured risk scoring
4. **Save results** for Notebook 05 (RGAT inference + augmented assessment)

**Risk framework:** Risk = Severity × Probability  
- **Severity** (1–10): Architectural importance — centrality, connectivity, cross-module influence  
- **Probability** (1–10): Likelihood that the change propagates through dependency pathways  

### Prerequisites
- `GITHUB_TOKEN` environment variable (PAT with `public_repo` scope)
- `OPENAI_API_KEY` environment variable
- `model_output/node_index.json` from the preprocessing pipeline

## 0. Environment Setup

In [1]:
%pip install PyGithub openai --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 449.7/449.7 kB 33.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 80.9 MB/s eta 0:00:00

In [2]:
# ── Colab Setup ──────────────────────────────────────────────────────
import shutil, zipfile
from pathlib import Path
from google.colab import drive

drive.mount("/content/drive")

DRIVE_DIR = Path("/content/drive/MyDrive/MSAAI/capstone")
PROJECT_ROOT = Path("/content/rgat_project")
PROJECT_ROOT.mkdir(exist_ok=True)

# Always re-extract source code to pick up any changes
zip_src = DRIVE_DIR / "rgat_source.zip"
for pkg in ["rgat", "graph_builder"]:
    old = PROJECT_ROOT / pkg
    if old.exists():
        shutil.rmtree(old)
with zipfile.ZipFile(zip_src, "r") as zf:
    zf.extractall(PROJECT_ROOT)
print("✓ Source code extracted (fresh)")

for d in ["artifacts", "cache", "checkpoints", "experiment_outputs"]:
    (PROJECT_ROOT / d).mkdir(exist_ok=True)

print(f"PROJECT_ROOT = {PROJECT_ROOT}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✓ Source code extracted (fresh)
PROJECT_ROOT = /content/rgat_project

In [3]:
import os, sys, json, re, time, hashlib
from pathlib import Path
from collections import defaultdict
from typing import Dict, List, Optional, Tuple

import pandas as pd
import github
from github import Github, GithubException, RateLimitExceededException
from openai import OpenAI

# PROJECT_ROOT set in Colab setup cell
sys.path.insert(0, str(PROJECT_ROOT))

ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"
OUTPUT_DIR = PROJECT_ROOT / "experiment_outputs"
OUTPUT_DIR.mkdir(exist_ok=True)

# ── API Keys ──────────────────────────────────────────────────────────
secrets_path = DRIVE_DIR / "secrets.json"
assert secrets_path.exists(), (
    f"secrets.json not found at {secrets_path}.\n"
    "Run the one-time setup cell above first (paste your keys and execute it)."
)
with open(secrets_path) as _f:
    _secrets = json.load(_f)

GITHUB_TOKEN = _secrets["GITHUB_TOKEN"]
OPENAI_API_KEY = _secrets["OPENAI_API_KEY"]
assert GITHUB_TOKEN and not GITHUB_TOKEN.startswith("PASTE"), "Replace the placeholder GITHUB_TOKEN in the setup cell"
assert OPENAI_API_KEY and not OPENAI_API_KEY.startswith("PASTE"), "Replace the placeholder OPENAI_API_KEY in the setup cell"

gh = Github(auth=github.Auth.Token(GITHUB_TOKEN), per_page=100)
openai_client = OpenAI(api_key=OPENAI_API_KEY)

# Check rate limit (API varies by PyGithub version)
rl = gh.get_rate_limit()
try:
    remaining, limit = rl.core.remaining, rl.core.limit
except AttributeError:
    remaining, limit = rl.rate.remaining, rl.rate.limit
print("✓ Keys loaded from Drive secrets.json")
print(f"GitHub rate limit: {remaining}/{limit}")

✓ Keys loaded from Drive secrets.json
GitHub rate limit: 4987/5000

## 1. Configuration

Map the 13 graph repo short names to their GitHub `owner/repo` paths.

In [4]:
# ── Repo mapping: graph short name → GitHub owner/repo ─────────────
REPO_MAP = {
    "django":          "django/django",
    "drf":             "encode/django-rest-framework",
    "wagtail":         "wagtail/wagtail",
    "allauth":         "pennersr/django-allauth",
    "netbox":          "netbox-community/netbox",
    "saleor":          "saleor/saleor",
    "oscar":           "django-oscar/django-oscar",
    "filter":          "carltongibson/django-filter",
    "simplejwt":       "jazzband/djangorestframework-simplejwt",
    "drf_spectacular": "tfranzel/drf-spectacular",
    "guardian":         "django-guardian/django-guardian",
    "celery_beat":     "celery/django-celery-beat",
    "channels":        "django/channels",
}

PRS_PER_REPO = 5          # Target number of *usable* PRs per repo
MAX_FETCH_PER_REPO = 15   # Fetch extra to filter out PRs with no graph overlap
OPENAI_MODEL = "gpt-4o"

print(f"Repos: {len(REPO_MAP)}")
print(f"Target PRs/repo: {PRS_PER_REPO}")
print(f"OpenAI model: {OPENAI_MODEL}")

Repos: 13
Target PRs/repo: 5
OpenAI model: gpt-4o

## 2. Load Node Index

Build lookups for mapping file paths → module node IDs and function/class names → node IDs.

In [5]:
# ── Copy artifacts from Drive if needed ───────────────────────────────
import shutil as _shutil

drive_mo = DRIVE_DIR / "model_output"
if drive_mo.exists() and not (ARTIFACTS_DIR / "node_index.json").exists():
    for f in os.listdir(drive_mo):
        _shutil.copy2(drive_mo / f, ARTIFACTS_DIR / f)
    print(f"✓ Copied artifacts from {drive_mo}")

# Also copy best_model.pt to checkpoints for NB05
ckpt_dir = PROJECT_ROOT / "checkpoints"
if (ARTIFACTS_DIR / "best_model.pt").exists() and not (ckpt_dir / "best_model.pt").exists():
    _shutil.copy2(ARTIFACTS_DIR / "best_model.pt", ckpt_dir / "best_model.pt")
    print("✓ Copied best_model.pt to checkpoints/")

with open(ARTIFACTS_DIR / "node_index.json") as f:
    node_index = json.load(f)

print("Node counts per type:")
for ntype, mapping in node_index.items():
    print(f"  {ntype}: {len(mapping):,}")

Node counts per type:
  class: 26,478
  function: 81,479
  module: 12,117
  repo: 13

In [6]:
# ── Build fast lookup structures ─────────────────────────────────────

# module_lookup: (repo, dotted_module_path) → node_id
module_lookup: Dict[Tuple[str, str], str] = {}
for node_id in node_index.get("module", {}):
    # node_id format: mod::<repo>::<dotted.module>
    parts = node_id.split("::")
    if len(parts) >= 3:
        repo, mod_path = parts[1], parts[2]
        module_lookup[(repo, mod_path)] = node_id

# class_lookup: (repo, dotted_module, class_qualname) → node_id
class_lookup: Dict[Tuple[str, str, str], str] = {}
for node_id in node_index.get("class", {}):
    # node_id format: class::<repo>::<module>::<QualName>
    parts = node_id.split("::")
    if len(parts) >= 4:
        repo, mod_path, qualname = parts[1], parts[2], parts[3]
        class_lookup[(repo, mod_path, qualname)] = node_id

# func_lookup: (repo, dotted_module, func_qualname) → node_id
func_lookup: Dict[Tuple[str, str, str], str] = {}
for node_id in node_index.get("function", {}):
    # node_id format: func::<repo>::<module>::<qualname>
    parts = node_id.split("::")
    if len(parts) >= 4:
        repo, mod_path, qualname = parts[1], parts[2], parts[3]
        func_lookup[(repo, mod_path, qualname)] = node_id

# For reverse lookup: integer index → node_id
reverse_index: Dict[str, Dict[int, str]] = {}
for ntype, mapping in node_index.items():
    reverse_index[ntype] = {v: k for k, v in mapping.items()}

print(f"Module lookup entries: {len(module_lookup):,}")
print(f"Class lookup entries:  {len(class_lookup):,}")
print(f"Function lookup entries: {len(func_lookup):,}")

Module lookup entries: 12,117
Class lookup entries:  26,478
Function lookup entries: 81,479

## 3. File Path → Module Path Conversion

Convert GitHub file paths to Python dotted module paths and match against the graph.

In [7]:
def filepath_to_module_candidates(filepath: str) -> List[str]:
    """Convert a repo-relative file path to candidate dotted module paths.

    Tries multiple prefix-stripping strategies since repos have different
    source layouts (e.g., src/oscar/ vs django/).
    """
    if not filepath.endswith(".py"):
        return []

    # Normalise
    fp = filepath.replace("\\", "/")

    # Remove .py and convert to dotted
    base = fp[:-3]  # strip .py
    if base.endswith("/__init__"):
        base = base[:-9]  # strip /__init__

    candidates = []

    # Strategy 1: Direct conversion
    candidates.append(base.replace("/", "."))

    # Strategy 2: Strip common source prefixes
    for prefix in ["src/", "lib/", "source/"]:
        if fp.startswith(prefix):
            stripped = base[len(prefix):]
            candidates.append(stripped.replace("/", "."))

    # Strategy 3: Strip first path component (repo-name directory)
    parts = base.split("/")
    if len(parts) > 1:
        candidates.append(".".join(parts[1:]))

    return candidates


def find_module_node(repo_short: str, filepath: str) -> Optional[str]:
    """Try to match a file path to a module node in the graph."""
    candidates = filepath_to_module_candidates(filepath)
    for mod_path in candidates:
        key = (repo_short, mod_path)
        if key in module_lookup:
            return module_lookup[key]
    return None


# Quick test
test_cases = [
    ("django", "django/contrib/auth/models.py"),
    ("oscar", "src/oscar/apps/checkout/views.py"),
    ("drf", "rest_framework/serializers.py"),
    ("allauth", "allauth/account/forms.py"),
]
for repo, fpath in test_cases:
    result = find_module_node(repo, fpath)
    print(f"  {repo}/{fpath} → {result or 'NOT FOUND'}")

  django/django/contrib/auth/models.py → mod::django::django.contrib.auth.models
  oscar/src/oscar/apps/checkout/views.py → mod::oscar::src.oscar.apps.checkout.views
  drf/rest_framework/serializers.py → mod::drf::rest_framework.serializers
  allauth/allauth/account/forms.py → mod::allauth::allauth.account.forms

## 4. Diff Parsing — Extract Changed Entities

Parse unified diffs to identify which functions and classes were modified,
then map them to graph node IDs.

In [8]:
def parse_diff_entities(diff_text: str, repo_short: str) -> Dict:
    """Parse a unified diff and extract changed entities mapped to graph nodes.

    Returns a dict with:
      - changed_files: list of file paths
      - matched_modules: list of (node_id, filepath)
      - matched_classes: list of (node_id, class_name)
      - matched_functions: list of (node_id, func_name)
      - unmatched_files: files with no graph module match
    """
    result = {
        "changed_files": [],
        "matched_modules": [],
        "matched_classes": [],
        "matched_functions": [],
        "unmatched_files": [],
    }

    current_file = None
    current_module_path = None  # dotted module path if matched
    hunk_context_class = None   # class name from @@ hunk header

    for line in diff_text.split("\n"):
        # ── New file in diff ──
        if line.startswith("diff --git"):
            # Reset context
            hunk_context_class = None
            # Extract b-side path: diff --git a/path b/path
            match = re.search(r" b/(.+)$", line)
            if match:
                current_file = match.group(1)
                result["changed_files"].append(current_file)

                if current_file.endswith(".py"):
                    node_id = find_module_node(repo_short, current_file)
                    if node_id:
                        result["matched_modules"].append((node_id, current_file))
                        # Extract dotted path from node_id for class/func lookup
                        current_module_path = node_id.split("::")[2]
                    else:
                        result["unmatched_files"].append(current_file)
                        current_module_path = None
                else:
                    current_module_path = None
            continue

        # ── Hunk header — extract context (function/class scope) ──
        if line.startswith("@@") and current_module_path:
            # Format: @@ -start,count +start,count @@ <context>
            ctx_match = re.search(r"@@.*?@@\s*(.+)", line)
            if ctx_match:
                ctx = ctx_match.group(1).strip()
                # Check for class context
                cls_match = re.match(r"class\s+(\w+)", ctx)
                if cls_match:
                    hunk_context_class = cls_match.group(1)
                # Check for function context
                func_match = re.match(r"(?:async\s+)?def\s+(\w+)", ctx)
                if func_match:
                    func_name = func_match.group(1)
                    # If we're inside a class, use Class.method qualname
                    if hunk_context_class:
                        qualname = f"{hunk_context_class}.{func_name}"
                    else:
                        qualname = func_name
                    key = (repo_short, current_module_path, qualname)
                    if key in func_lookup:
                        result["matched_functions"].append(
                            (func_lookup[key], qualname)
                        )
            continue

        # ── Added/removed lines — detect new def/class definitions ──
        if (line.startswith("+") or line.startswith("-")) and not line.startswith("+++") and not line.startswith("---"):
            code = line[1:].strip()

            if current_module_path:
                # Class definition
                cls_def = re.match(r"class\s+(\w+)", code)
                if cls_def:
                    cls_name = cls_def.group(1)
                    hunk_context_class = cls_name  # update context
                    key = (repo_short, current_module_path, cls_name)
                    if key in class_lookup:
                        result["matched_classes"].append(
                            (class_lookup[key], cls_name)
                        )

                # Function definition
                func_def = re.match(r"(?:async\s+)?def\s+(\w+)", code)
                if func_def:
                    func_name = func_def.group(1)
                    # Try Class.method qualname first if we have class context
                    matched = False
                    if hunk_context_class:
                        qualname = f"{hunk_context_class}.{func_name}"
                        key = (repo_short, current_module_path, qualname)
                        if key in func_lookup:
                            result["matched_functions"].append(
                                (func_lookup[key], qualname)
                            )
                            matched = True
                    if not matched:
                        # Try as top-level function
                        key = (repo_short, current_module_path, func_name)
                        if key in func_lookup:
                            result["matched_functions"].append(
                                (func_lookup[key], func_name)
                            )

    # Deduplicate
    for key in ["matched_modules", "matched_classes", "matched_functions"]:
        result[key] = list(dict.fromkeys(result[key]))

    return result


print("✓ Diff parser ready")

✓ Diff parser ready

## 5. Fetch PRs from GitHub

For each repo, fetch recent merged PRs, extract the diff, and map changed entities to graph nodes.
Only keep PRs that have at least one matching node in the graph.

In [9]:
def fetch_pr_diff(repo_obj, pr) -> Optional[str]:
    """Fetch the diff text for a PR, respecting rate limits."""
    try:
        # Get diff via the pulls API
        import urllib.request
        url = pr.diff_url
        req = urllib.request.Request(url)
        req.add_header("Authorization", f"token {GITHUB_TOKEN}")
        req.add_header("Accept", "application/vnd.github.v3.diff")
        with urllib.request.urlopen(req) as resp:
            return resp.read().decode("utf-8", errors="replace")
    except Exception as e:
        print(f"  ⚠ Failed to fetch diff for PR #{pr.number}: {e}")
        return None


def fetch_prs_for_repo(
    repo_short: str,
    github_path: str,
    target_count: int = PRS_PER_REPO,
    max_fetch: int = MAX_FETCH_PER_REPO,
) -> List[Dict]:
    """Fetch recent merged PRs for a repo and map to graph nodes."""
    print(f"\n{'='*60}")
    print(f"Fetching PRs for {repo_short} ({github_path})")
    print(f"{'='*60}")

    repo_obj = gh.get_repo(github_path)
    pulls = repo_obj.get_pulls(state="closed", sort="updated", direction="desc")

    collected = []
    checked = 0

    for pr in pulls:
        if checked >= max_fetch or len(collected) >= target_count:
            break

        # Only merged PRs
        if not pr.merged:
            continue

        checked += 1

        # Skip very large PRs (>50 files) — too noisy for risk assessment
        if pr.changed_files > 50:
            print(f"  Skipping PR #{pr.number} ({pr.changed_files} files — too large)")
            continue

        # Fetch diff
        diff_text = fetch_pr_diff(repo_obj, pr)
        if not diff_text:
            continue

        # Truncate very long diffs for LLM context (keep first 12k chars)
        diff_truncated = diff_text[:12000]
        if len(diff_text) > 12000:
            diff_truncated += f"\n\n... [diff truncated: {len(diff_text):,} chars total, showing first 12,000]"

        # Map to graph nodes
        entities = parse_diff_entities(diff_text, repo_short)

        total_matched = (
            len(entities["matched_modules"])
            + len(entities["matched_classes"])
            + len(entities["matched_functions"])
        )

        if total_matched == 0:
            print(f"  Skipping PR #{pr.number} — no graph overlap")
            continue

        pr_data = {
            "repo_short": repo_short,
            "github_path": github_path,
            "pr_number": pr.number,
            "pr_title": pr.title,
            "pr_url": pr.html_url,
            "pr_body": (pr.body or "")[:2000],
            "merged_at": str(pr.merged_at),
            "changed_files_count": pr.changed_files,
            "additions": pr.additions,
            "deletions": pr.deletions,
            "diff_text": diff_truncated,
            "diff_full_length": len(diff_text),
            "entities": {
                "changed_files": entities["changed_files"],
                "matched_modules": [(nid, fp) for nid, fp in entities["matched_modules"]],
                "matched_classes": [(nid, cn) for nid, cn in entities["matched_classes"]],
                "matched_functions": [(nid, fn) for nid, fn in entities["matched_functions"]],
                "unmatched_files": entities["unmatched_files"],
            },
            "total_matched_nodes": total_matched,
        }

        collected.append(pr_data)
        print(
            f"  ✓ PR #{pr.number}: \"{pr.title[:60]}\" — "
            f"{total_matched} matched nodes "
            f"({len(entities['matched_modules'])}M/{len(entities['matched_classes'])}C/{len(entities['matched_functions'])}F)"
        )

        # Brief pause to be polite to GitHub API
        time.sleep(0.5)

    print(f"\n  Collected {len(collected)}/{target_count} PRs for {repo_short}")
    return collected


print("✓ PR fetcher ready")

✓ PR fetcher ready

In [10]:
# ── Fetch PRs from all repos ─────────────────────────────────────────
all_prs: List[Dict] = []

for repo_short, github_path in REPO_MAP.items():
    try:
        prs = fetch_prs_for_repo(repo_short, github_path)
        all_prs.extend(prs)
    except RateLimitExceededException:
        reset_time = gh.get_rate_limit().core.reset
        print(f"\n⚠ Rate limited! Resets at {reset_time}. Sleeping...")
        wait = (reset_time - __import__('datetime').datetime.now(
            __import__('datetime').timezone.utc
        )).total_seconds() + 10
        time.sleep(max(wait, 0))
        # Retry this repo
        prs = fetch_prs_for_repo(repo_short, github_path)
        all_prs.extend(prs)
    except GithubException as e:
        print(f"\n⚠ GitHub error for {repo_short}: {e}")

print(f"\n{'='*60}")
print(f"Total PRs collected: {len(all_prs)}")
print(f"Repos represented: {len(set(p['repo_short'] for p in all_prs))}")
print(f"Total matched nodes: {sum(p['total_matched_nodes'] for p in all_prs)}")

============================================================
Fetching PRs for django (django/django)
============================================================
  ✓ PR #21050: "Refs #36949 -- Removed hardcoded pks in modeladmin tests." — 1 matched nodes (1M/0C/0F)
  ✓ PR #21046: "Fixed #37016 -- Avoided propagating invalid arguments from W" — 4 matched nodes (4M/0C/0F)
  ✓ PR #20889: "Fixed #36973 -- Made fields.E348 detect accessor and manager" — 2 matched nodes (2M/0C/0F)
  Skipping PR #21047 — no graph overlap
  ✓ PR #20027: "Fixed #20024 -- Fixed handling of __in lookups with None in " — 3 matched nodes (3M/0C/0F)
  ✓ PR #21035: "Fixed #36949 -- Improved RelatedFieldWidgetWrapper <labels>." — 4 matched nodes (3M/0C/1F)

  Collected 5/5 PRs for django

============================================================
Fetching PRs for drf (encode/django-rest-framework)
============================================================
  ✓ PR #9902: "Fix partial form data updates involving `ListField`" — 3 matched nodes (3M/0C/0F)
  Skipping PR #9905 — no graph overlap
  Skipping PR #9935 — no graph overlap
  Skipping PR #9936 — no graph overlap
  ✓ PR #9929: "Include `choices` param for non-editable fields" — 3 matched nodes (2M/0C/1F)
  ✓ PR #9931: "Prepare bug fix release 3.17.1" — 1 matched nodes (1M/0C/0F)
  Skipping PR #9924 — no graph overlap
  ✓ PR #9928: "Fix `HTMLFormRenderer` with empty `datetime` values" — 2 matched nodes (2M/0C/0F)
  ✓ PR #9735: "Preserve ordering in `MultipleChoiceField`" — 6 matched nodes (3M/0C/3F)

  Collected 5/5 PRs for drf

============================================================
Fetching PRs for wagtail (wagtail/wagtail)
============================================================
  Skipping PR #14091 — no graph overlap
  Skipping PR #14093 — no graph overlap
  ✓ PR #14017: "Store preview data in a dedicated FormState model" — 15 matched nodes (7M/0C/8F)
  ✓ PR #14034: "Use the same UUID for autosave audit logs and group them in " — 11 matched nodes (9M/1C/1F)
  Skipping PR #14079 — no graph overlap
  Skipping PR #14070 — no graph overlap
  Skipping PR #14071 — no graph overlap
  Skipping PR #14056 — no graph overlap
  ✓ PR #13930: "Defer validation of required fields within StreamField (v2)" — 16 matched nodes (16M/0C/0F)
  ✓ PR #13975: "Autosave UX improvements" — 10 matched nodes (7M/0C/3F)
  ✓ PR #13974: "Avoid creating a new editing session when updating UI elemen" — 4 matched nodes (4M/0C/0F)

  Collected 5/5 PRs for wagtail

============================================================
Fetching PRs for allauth (pennersr/django-allauth)
============================================================

⚠ GitHub error for allauth: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/pulls/pulls#list-pull-requests", "status": "404"}

============================================================
Fetching PRs for netbox (netbox-community/netbox)
============================================================
  ✓ PR #21837: "Closes #21795: Improve humanize_speed formatting for decimal" — 3 matched nodes (2M/0C/1F)
  ✓ PR #21816: "Closes #21770: Enable including/excluding columns on Objects" — 13 matched nodes (11M/0C/2F)
  Skipping PR #21838 — no graph overlap
  Skipping PR #21840 — no graph overlap
  ✓ PR #21815: "Fixes #21498: Fix Exception when changing a Cable Terminatio" — 9 matched nodes (5M/0C/4F)
  ✓ PR #21829: "Fixes: #21535 - Fix filtering of object-type custom fields w" — 4 matched nodes (3M/0C/1F)
  ✓ PR #21805: "Fixes: #21696 - Upgrade to django-rq==4.0.1" — 11 matched nodes (6M/0C/5F)

  Collected 5/5 PRs for netbox

============================================================
Fetching PRs for saleor (saleor/saleor)
============================================================
  ✓ PR #17890: "[3.20] Add support for Kosovo country" — 7 matched nodes (4M/2C/1F)
  ✓ PR #17979: "Fix checkout.discount amount when override is set" — 7 matched nodes (3M/0C/4F)
  ✓ PR #19011: "Turn off deferred for fulfillment events that are using dict" — 1 matched nodes (1M/0C/0F)
  ✓ PR #19012: "Turn off deferred for fulfillment events that are using dict" — 1 matched nodes (1M/0C/0F)
  ✓ PR #17687: "Add missing migrations and fix failing tests" — 8 matched nodes (4M/3C/1F)

  Collected 5/5 PRs for saleor

============================================================
Fetching PRs for oscar (django-oscar/django-oscar)
============================================================
  ✓ PR #4521: "use get_extra_context for the confirmation email" — 1 matched nodes (1M/0C/0F)
  ✓ PR #4558: "[FEAT] Make email search more flexible" — 2 matched nodes (2M/0C/0F)
  ✓ PR #4556: "deps: compatibility with django-treebeard 5.0" — 4 matched nodes (2M/0C/2F)
  ✓ PR #4552: "[FEAT] Add code in product review" — 4 matched nodes (3M/1C/0F)
  ✓ PR #4551: "[FEAT] Add code in address models" — 17 matched nodes (13M/4C/0F)

  Collected 5/5 PRs for oscar

============================================================
Fetching PRs for filter (carltongibson/django-filter)
============================================================
  Skipping PR #1283 — no graph overlap
  ✓ PR #1270: "Run tests against Python 3.9" — 3 matched nodes (1M/1C/1F)
  Skipping PR #1733 — no graph overlap
  Skipping PR #1730 — no graph overlap
  Skipping PR #1731 — no graph overlap
  Skipping PR #1726 — no graph overlap
  Skipping PR #1722 — no graph overlap
  Skipping PR #1724 — no graph overlap
  ✓ PR #1706: "Add reference anchors to filter types to facilitate intersph" — 1 matched nodes (1M/0C/0F)
  Skipping PR #1704 — no graph overlap
  ✓ PR #1703: "Replace hardcoded pks in tests" — 3 matched nodes (3M/0C/0F)
  Skipping PR #1700 — no graph overlap
  ✓ PR #1691: "Cast data to QueryDict in LinkWidget.render_option" — 2 matched nodes (2M/0C/0F)
  Skipping PR #1699 — no graph overlap
  ✓ PR #1698: "Removed deprecated schema generation methods from DRF backen" — 5 matched nodes (4M/0C/1F)

  Collected 5/5 PRs for filter

============================================================
Fetching PRs for simplejwt (jazzband/djangorestframework-simplejwt)
============================================================
  Skipping PR #951 — no graph overlap
  Skipping PR #962 — no graph overlap
  Skipping PR #955 — no graph overlap
  ✓ PR #966: "chore: bump python-jose" — 1 matched nodes (1M/0C/0F)
  ✓ PR #964: "Add importlib to doc dependencies" — 1 matched nodes (1M/0C/0F)
  ✓ PR #963: "fix: use curve-matching EC keys for ES384/ES512 backend test" — 2 matched nodes (2M/0C/0F)
  ✓ PR #959: "feat: add django 6.0 and python 3.14 support" — 3 matched nodes (2M/0C/1F)
  Skipping PR #956 — no graph overlap
  ✓ PR #887: "fix: always stringify user_id claim" — 6 matched nodes (6M/0C/0F)

  Collected 5/5 PRs for simplejwt

============================================================
Fetching PRs for drf_spectacular (tfranzel/drf-spectacular)
============================================================
  ✓ PR #1469: "Fix regression introduced in #1450" — 2 matched nodes (2M/0C/0F)
  ✓ PR #1467: "Add l18n handling for Decimal field #1466" — 2 matched nodes (2M/0C/0F)
  ✓ PR #1450: "[django-filter] Add null_label if set in ChoiceFilter" — 3 matched nodes (2M/0C/1F)
  ✓ PR #1416: "Fix memory leak" — 1 matched nodes (1M/0C/0F)
  ✓ PR #1465: "Update linting packages and fix new issues" — 15 matched nodes (10M/0C/5F)

  Collected 5/5 PRs for drf_spectacular

============================================================
Fetching PRs for guardian (django-guardian/django-guardian)
============================================================
  ✓ PR #974: "Fixed user and group inconsistency with get perms" — 2 matched nodes (2M/0C/0F)
  Skipping PR #973 — no graph overlap
  Skipping PR #979 — no graph overlap
  ✓ PR #976: "Issue966" — 2 matched nodes (2M/0C/0F)
  Skipping PR #978 — no graph overlap
  Skipping PR #977 — no graph overlap
  Skipping PR #975 — no graph overlap
  Skipping PR #971 — no graph overlap
  Skipping PR #970 — no graph overlap
  ✓ PR #969: "Fix possible IndexError when trying to bulk-assign permissio" — 2 matched nodes (2M/0C/0F)
  ✓ PR #962: "Improve managers typing and reduce code duplication" — 3 matched nodes (1M/0C/2F)
  Skipping PR #965 — no graph overlap
  Skipping PR #964 — no graph overlap
  Skipping PR #960 — no graph overlap
  Skipping PR #959 — no graph overlap

  Collected 4/5 PRs for guardian

============================================================
Fetching PRs for celery_beat (celery/django-celery-beat)
============================================================
  Skipping PR #1014 — no graph overlap
  Skipping PR #1013 — no graph overlap
  ✓ PR #1009: "Fix cron-descriptor >= 2.0 compatibility" — 2 matched nodes (2M/0C/0F)
  Skipping PR #1012 — no graph overlap
  ✓ PR #986: "Allow pytest 9" — 1 matched nodes (1M/0C/0F)
  Skipping PR #1011 — no graph overlap
  Skipping PR #1010 — no graph overlap
  Skipping PR #1008 — no graph overlap
  Skipping PR #1007 — no graph overlap
  Skipping PR #1006 — no graph overlap
  Skipping PR #1005 — no graph overlap
  ✓ PR #999: "django_celery_beat v2.9.0" — 1 matched nodes (1M/0C/0F)
  Skipping PR #1004 — no graph overlap
  Skipping PR #1003 — no graph overlap
  Skipping PR #1002 — no graph overlap

  Collected 3/5 PRs for celery_beat

============================================================
Fetching PRs for channels (django/channels)
============================================================
  ✓ PR #2217: "Add missing newline in manage.py for black 26 compatibility" — 1 matched nodes (1M/0C/0F)
  Skipping PR #2216 — no graph overlap
  Skipping PR #2213 — no graph overlap
  Skipping PR #2199 — no graph overlap
  Skipping PR #2207 — no graph overlap
  Skipping PR #2206 — no graph overlap
  Skipping PR #2204 — no graph overlap
  ✓ PR #2202: "Fix selenium test flakiness" — 5 matched nodes (2M/0C/3F)
  Skipping PR #2200 — no graph overlap
  Skipping PR #2198 — no graph overlap
  Skipping PR #2184 — no graph overlap
  Skipping PR #2183 — no graph overlap
  Skipping PR #2180 — no graph overlap
  Skipping PR #2170 — no graph overlap
  ✓ PR #2178: "Update set_database_connection to fix #2176" — 3 matched nodes (2M/0C/1F)

  Collected 3/5 PRs for channels

============================================================
Total PRs collected: 55
Repos represented: 12
Total matched nodes: 249

In [11]:
# ── Summary table ────────────────────────────────────────────────────
summary = []
for pr in all_prs:
    e = pr["entities"]
    summary.append({
        "repo": pr["repo_short"],
        "PR": f"#{pr['pr_number']}",
        "title": pr["pr_title"][:50],
        "files": pr["changed_files_count"],
        "modules": len(e["matched_modules"]),
        "classes": len(e["matched_classes"]),
        "functions": len(e["matched_functions"]),
        "total_nodes": pr["total_matched_nodes"],
        "unmatched": len(e["unmatched_files"]),
    })

df_summary = pd.DataFrame(summary)
print(f"\nTotal: {len(df_summary)} PRs, {df_summary['total_nodes'].sum()} matched nodes")
display(df_summary)

Total: 55 PRs, 249 matched nodes

,repo,PR,title,files,modules,classes,functions,total_nodes,unmatched
0,django,#21050,Refs #36949 -- Removed hardcoded pks in modela...,1,1,0,0,1,0
1,django,#21046,Fixed #37016 -- Avoided propagating invalid ar...,4,4,0,0,4,0
2,django,#20889,Fixed #36973 -- Made fields.E348 detect access...,3,2,0,0,2,0
3,django,#20027,Fixed #20024 -- Fixed handling of __in lookups...,3,3,0,0,3,0
4,django,#21035,Fixed #36949 -- Improved RelatedFieldWidgetWra...,4,3,0,1,4,0
5,drf,#9902,Fix partial form data updates involving `ListF...,4,3,0,0,3,0
6,drf,#9929,Include `choices` param for non-editable fields,2,2,0,1,3,0
7,drf,#9931,Prepare bug fix release 3.17.1,2,1,0,0,1,0
8,drf,#9928,Fix `HTMLFormRenderer` with empty `datetime` v...,2,2,0,0,2,0
9,drf,#9735,Preserve ordering in `MultipleChoiceField`,4,3,0,3,6,0
10,wagtail,#14017,Store preview data in a dedicated FormState model,10,7,0,8,15,1
11,wagtail,#14034,Use the same UUID for autosave audit logs and ...,14,9,1,1,11,1
12,wagtail,#13930,Defer validation of required fields within Str...,21,16,0,0,16,0
13,wagtail,#13975,Autosave UX improvements,15,7,0,3,10,0
14,wagtail,#13974,Avoid creating a new editing session when upda...,6,4,0,0,4,0
15,netbox,#21837,Closes #21795: Improve humanize_speed formatti...,2,2,0,1,3,0
16,netbox,#21816,Closes #21770: Enable including/excluding colu...,11,11,0,2,13,0
17,netbox,#21815,Fixes #21498: Fix Exception when changing a Ca...,5,5,0,4,9,0
18,netbox,#21829,Fixes: #21535 - Fix filtering of object-type c...,3,3,0,1,4,0
19,netbox,#21805,Fixes: #21696 - Upgrade to django-rq==4.0.1,7,6,0,5,11,0
20,saleor,#17890,[3.20] Add support for Kosovo country,6,4,2,1,7,0
21,saleor,#17979,Fix checkout.discount amount when override is set,3,3,0,4,7,0
22,saleor,#19011,Turn off deferred for fulfillment events that ...,1,1,0,0,1,0
23,saleor,#19012,Turn off deferred for fulfillment events that ...,1,1,0,0,1,0
24,saleor,#17687,Add missing migrations and fix failing tests,4,4,3,1,8,0
25,oscar,#4521,use get_extra_context for the confirmation email,1,1,0,0,1,0
26,oscar,#4558,[FEAT] Make email search more flexible,2,2,0,0,2,0
27,oscar,#4556,deps: compatibility with django-treebeard 5.0,3,2,0,2,4,0
28,oscar,#4552,[FEAT] Add code in product review,3,3,1,0,4,0
29,oscar,#4551,[FEAT] Add code in address models,14,13,4,0,17,0
30,filter,#1270,Run tests against Python 3.9,5,1,1,1,3,1
31,filter,#1706,Add reference anchors to filter types to facil...,7,1,0,0,1,0
32,filter,#1703,Replace hardcoded pks in tests,3,3,0,0,3,0
33,filter,#1691,Cast data to QueryDict in LinkWidget.render_op...,2,2,0,0,2,0
34,filter,#1698,Removed deprecated schema generation methods f...,6,4,0,1,5,0
35,simplejwt,#966,chore: bump python-jose,1,1,0,0,1,0
36,simplejwt,#964,Add importlib to doc dependencies,1,1,0,0,1,0
37,simplejwt,#963,fix: use curve-matching EC keys for ES384/ES51...,2,2,0,0,2,0
38,simplejwt,#959,feat: add django 6.0 and python 3.14 support,6,2,0,1,3,0
39,simplejwt,#887,fix: always stringify user_id claim,7,6,0,0,6,0
40,drf_spectacular,#1469,Fix regression introduced in #1450,2,2,0,0,2,0
41,drf_spectacular,#1467,Add l18n handling for Decimal field #1466,3,2,0,0,2,0
42,drf_spectacular,#1450,[django-filter] Add null_label if set in Choic...,2,2,0,1,3,0
43,drf_spectacular,#1416,Fix memory leak,1,1,0,0,1,0
44,drf_spectacular,#1465,Update linting packages and fix new issues,13,10,0,5,15,0
45,guardian,#974,Fixed user and group inconsistency with get perms,3,2,0,0,2,0
46,guardian,#976,Issue966,2,2,0,0,2,0
47,guardian,#969,Fix possible IndexError when trying to bulk-as...,2,2,0,0,2,0
48,guardian,#962,Improve managers typing and reduce code duplic...,1,1,0,2,3,0
49,celery_beat,#1009,Fix cron-descriptor >= 2.0 compatibility,3,2,0,0,2,0
50,celery_beat,#986,Allow pytest 9,2,1,0,0,1,0
51,celery_beat,#999,django_celery_beat v2.9.0,3,1,0,0,1,0
52,channels,#2217,Add missing newline in manage.py for black 26 ...,1,1,0,0,1,0
53,channels,#2202,Fix selenium test flakiness,3,2,0,3,5,0
54,channels,#2178,Update set_database_connection to fix #2176,5,2,0,1,3,0

## 6. LLM-Only Risk Assessment

Prompt GPT-4o with **only** the PR diff and metadata — no structural/graph context.
This establishes the baseline for comparison with the RGAT-augmented version.

In [12]:
RISK_SYSTEM_PROMPT = """You are an expert software architect specialising in change risk assessment for large Python ecosystems.

You will be given a pull request diff from an open-source Django ecosystem project. Your task is to assess the **change risk** of this PR.

Risk is defined as: **Risk = Severity × Probability**

**Severity (1–10):** The intrinsic architectural importance of the components being changed.
Consider:
- Is the code a core module vs. peripheral utility?
- How many other components likely depend on this code?
- Does the change affect public APIs, base classes, or interfaces?
- Could the change break backwards compatibility?
- Is the code in a critical path (auth, data access, serialization, etc.)?

**Probability (1–10):** The likelihood that this specific change will cause issues to propagate.
Consider:
- How invasive is the change (refactor vs. bug fix vs. new feature)?
- Does it change function signatures, class hierarchies, or return types?
- Could downstream consumers of these APIs be affected?
- Are there implicit contracts being modified?
- How much of the codebase could be transitively affected?

**Respond with valid JSON only**, matching this exact schema:
```json
{
  "severity": <int 1-10>,
  "severity_reasoning": "<2-3 sentences explaining the severity score>",
  "probability": <int 1-10>,
  "probability_reasoning": "<2-3 sentences explaining the probability score>",
  "risk_score": <int: severity * probability>,
  "risk_level": "<low|medium|high|critical>",
  "key_risks": ["<risk 1>", "<risk 2>", ...],
  "affected_areas": ["<area 1>", "<area 2>", ...],
  "summary": "<1 paragraph overall risk summary>"
}
```

Risk level thresholds: low (1-15), medium (16-35), high (36-64), critical (65-100).
"""


def build_llm_only_prompt(pr_data: Dict) -> str:
    """Build the user prompt for LLM-only risk assessment."""
    entities = pr_data["entities"]
    changed_files_str = "\n".join(f"  - {f}" for f in entities["changed_files"][:20])
    if len(entities["changed_files"]) > 20:
        changed_files_str += f"\n  ... and {len(entities['changed_files']) - 20} more"

    prompt = f"""## Pull Request: {pr_data['pr_title']}
**Repository:** {pr_data['github_path']}
**PR:** #{pr_data['pr_number']} ({pr_data['pr_url']})
**Files changed:** {pr_data['changed_files_count']} (+{pr_data['additions']}/−{pr_data['deletions']})
**Merged:** {pr_data['merged_at']}

### PR Description
{pr_data['pr_body'][:1000] if pr_data['pr_body'] else '(no description)'}

### Changed Files
{changed_files_str}

### Diff
```diff
{pr_data['diff_text']}
```

Analyse this PR and provide your structured risk assessment as JSON.
"""
    return prompt


print("✓ LLM-only prompt builder ready")
print(f"System prompt length: {len(RISK_SYSTEM_PROMPT):,} chars")

✓ LLM-only prompt builder ready
System prompt length: 1,728 chars

In [13]:
def call_openai_risk_assessment(
    system_prompt: str,
    user_prompt: str,
    model: str = OPENAI_MODEL,
    max_retries: int = 3,
) -> Optional[Dict]:
    """Call OpenAI API and parse structured JSON response."""
    for attempt in range(max_retries):
        try:
            response = openai_client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.2,
                response_format={"type": "json_object"},
                max_tokens=1000,
            )

            content = response.choices[0].message.content
            result = json.loads(content)

            # Basic validation
            required = ["severity", "probability", "risk_score", "risk_level", "summary"]
            if all(k in result for k in required):
                result["_model"] = model
                result["_tokens"] = {
                    "prompt": response.usage.prompt_tokens,
                    "completion": response.usage.completion_tokens,
                }
                return result
            else:
                missing = [k for k in required if k not in result]
                print(f"  ⚠ Missing keys: {missing}. Retrying...")

        except json.JSONDecodeError as e:
            print(f"  ⚠ JSON parse error (attempt {attempt+1}): {e}")
        except Exception as e:
            print(f"  ⚠ API error (attempt {attempt+1}): {e}")
            time.sleep(2 ** attempt)  # exponential backoff

    return None


print("✓ OpenAI caller ready")

✓ OpenAI caller ready

In [14]:
# ── Run LLM-only risk assessment ─────────────────────────────────────
llm_only_results = []

for i, pr_data in enumerate(all_prs):
    pr_id = f"{pr_data['repo_short']}#{pr_data['pr_number']}"
    print(f"[{i+1}/{len(all_prs)}] Assessing {pr_id}: {pr_data['pr_title'][:50]}...")

    user_prompt = build_llm_only_prompt(pr_data)
    assessment = call_openai_risk_assessment(RISK_SYSTEM_PROMPT, user_prompt)

    if assessment:
        print(
            f"  → Risk: {assessment['risk_score']} ({assessment['risk_level']}) "
            f"[S={assessment['severity']} × P={assessment['probability']}]"
        )
    else:
        print(f"  ✗ Failed to get assessment")
        assessment = {"error": "API call failed"}

    llm_only_results.append({
        "pr_id": pr_id,
        "repo_short": pr_data["repo_short"],
        "pr_number": pr_data["pr_number"],
        "pr_title": pr_data["pr_title"],
        "assessment": assessment,
    })

    time.sleep(0.5)  # Rate limit courtesy

print(f"\n✓ Completed {len(llm_only_results)} LLM-only assessments")

[1/55] Assessing django#21050: Refs #36949 -- Removed hardcoded pks in modeladmin...
  → Risk: 2 (low) [S=2 × P=1]
[2/55] Assessing django#21046: Fixed #37016 -- Avoided propagating invalid argume...
  → Risk: 24 (medium) [S=6 × P=4]
[3/55] Assessing django#20889: Fixed #36973 -- Made fields.E348 detect accessor a...
  → Risk: 24 (medium) [S=6 × P=4]
[4/55] Assessing django#20027: Fixed #20024 -- Fixed handling of __in lookups wit...
  → Risk: 35 (medium) [S=7 × P=5]
[5/55] Assessing django#21035: Fixed #36949 -- Improved RelatedFieldWidgetWrapper...
  → Risk: 20 (medium) [S=5 × P=4]
[6/55] Assessing drf#9902: Fix partial form data updates involving `ListField...
  → Risk: 24 (medium) [S=6 × P=4]
[7/55] Assessing drf#9929: Include `choices` param for non-editable fields...
  → Risk: 24 (medium) [S=6 × P=4]
[8/55] Assessing drf#9931: Prepare bug fix release 3.17.1...
  → Risk: 6 (low) [S=3 × P=2]
[9/55] Assessing drf#9928: Fix `HTMLFormRenderer` with empty `datetime` value...
  → Risk: 18 (medium) [S=6 × P=3]
[10/55] Assessing drf#9735: Preserve ordering in `MultipleChoiceField`...
  → Risk: 42 (high) [S=7 × P=6]
[11/55] Assessing wagtail#14017: Store preview data in a dedicated FormState model...
  → Risk: 42 (high) [S=7 × P=6]
[12/55] Assessing wagtail#14034: Use the same UUID for autosave audit logs and grou...
  → Risk: 42 (high) [S=7 × P=6]
[13/55] Assessing wagtail#13930: Defer validation of required fields within StreamF...
  → Risk: 42 (high) [S=7 × P=6]
[14/55] Assessing wagtail#13975: Autosave UX improvements...
  → Risk: 30 (medium) [S=6 × P=5]
[15/55] Assessing wagtail#13974: Avoid creating a new editing session when updating...
  → Risk: 24 (medium) [S=6 × P=4]
[16/55] Assessing netbox#21837: Closes #21795: Improve humanize_speed formatting f...
  → Risk: 12 (low) [S=4 × P=3]
[17/55] Assessing netbox#21816: Closes #21770: Enable including/excluding columns ...
  → Risk: 30 (medium) [S=6 × P=5]
[18/55] Assessing netbox#21815: Fixes #21498: Fix Exception when changing a Cable ...
  → Risk: 35 (medium) [S=7 × P=5]
[19/55] Assessing netbox#21829: Fixes: #21535 - Fix filtering of object-type custo...
  → Risk: 15 (low) [S=5 × P=3]
[20/55] Assessing netbox#21805: Fixes: #21696 - Upgrade to django-rq==4.0.1...
  → Risk: 35 (medium) [S=7 × P=5]
[21/55] Assessing saleor#17890: [3.20] Add support for Kosovo country...
  → Risk: 20 (medium) [S=5 × P=4]
[22/55] Assessing saleor#17979: Fix checkout.discount amount when override is set...
  → Risk: 24 (medium) [S=6 × P=4]
[23/55] Assessing saleor#19011: Turn off deferred for fulfillment events that are ...
  → Risk: 24 (medium) [S=6 × P=4]
[24/55] Assessing saleor#19012: Turn off deferred for fulfillment events that are ...
  → Risk: 24 (medium) [S=6 × P=4]
[25/55] Assessing saleor#17687: Add missing migrations and fix failing tests...
  → Risk: 24 (medium) [S=6 × P=4]
[26/55] Assessing oscar#4521: use get_extra_context for the confirmation email...
  → Risk: 20 (medium) [S=5 × P=4]
[27/55] Assessing oscar#4558: [FEAT] Make email search more flexible...
  → Risk: 12 (low) [S=4 × P=3]
[28/55] Assessing oscar#4556: deps: compatibility with django-treebeard 5.0...
  → Risk: 24 (medium) [S=6 × P=4]
[29/55] Assessing oscar#4552: [FEAT] Add code in product review...
  → Risk: 24 (medium) [S=6 × P=4]
[30/55] Assessing oscar#4551: [FEAT] Add code in address models...
  → Risk: 42 (high) [S=7 × P=6]
[31/55] Assessing filter#1270: Run tests against Python 3.9...
  → Risk: 6 (low) [S=3 × P=2]
[32/55] Assessing filter#1706: Add reference anchors to filter types to facilitat...
  → Risk: 6 (low) [S=3 × P=2]
[33/55] Assessing filter#1703: Replace hardcoded pks in tests...
  → Risk: 2 (low) [S=2 × P=1]
[34/55] Assessing filter#1691: Cast data to QueryDict in LinkWidget.render_option...
  → Risk: 24 (medium) [S=6 × P=4]
[35/55] Assessing filter#1698: Removed deprecated schema generation methods from ...
  → Risk: 35 (medium) [S=7 × P=5]
[36/55] Assessing simplejwt#966: chore: bump python-jose...
  → Risk: 28 (medium) [S=7 × P=4]
[37/55] Assessing simplejwt#964: Add importlib to doc dependencies...
  → Risk: 2 (low) [S=2 × P=1]
[38/55] Assessing simplejwt#963: fix: use curve-matching EC keys for ES384/ES512 ba...
  → Risk: 8 (low) [S=4 × P=2]
[39/55] Assessing simplejwt#959: feat: add django 6.0 and python 3.14 support...
  → Risk: 20 (medium) [S=5 × P=4]
[40/55] Assessing simplejwt#887: fix: always stringify user_id claim...
  → Risk: 42 (high) [S=7 × P=6]
[41/55] Assessing drf_spectacular#1469: Fix regression introduced in #1450...
  → Risk: 15 (low) [S=5 × P=3]
[42/55] Assessing drf_spectacular#1467: Add l18n handling for Decimal field #1466...
  → Risk: 24 (medium) [S=6 × P=4]
[43/55] Assessing drf_spectacular#1450: [django-filter] Add null_label if set in ChoiceFil...
  → Risk: 20 (medium) [S=5 × P=4]
[44/55] Assessing drf_spectacular#1416: Fix memory leak...
  → Risk: 24 (medium) [S=6 × P=4]
[45/55] Assessing drf_spectacular#1465: Update linting packages and fix new issues...
  → Risk: 6 (low) [S=3 × P=2]
[46/55] Assessing guardian#974: Fixed user and group inconsistency with get perms...
  → Risk: 35 (medium) [S=7 × P=5]
[47/55] Assessing guardian#976: Issue966...
  → Risk: 35 (medium) [S=7 × P=5]
[48/55] Assessing guardian#969: Fix possible IndexError when trying to bulk-assign...
  → Risk: 15 (low) [S=5 × P=3]
[49/55] Assessing guardian#962: Improve managers typing and reduce code duplicatio...
  → Risk: 24 (medium) [S=6 × P=4]
[50/55] Assessing celery_beat#1009: Fix cron-descriptor >= 2.0 compatibility...
  → Risk: 24 (medium) [S=6 × P=4]
[51/55] Assessing celery_beat#986: Allow pytest 9...
  → Risk: 6 (low) [S=3 × P=2]
[52/55] Assessing celery_beat#999: django_celery_beat v2.9.0...
  → Risk: 6 (low) [S=3 × P=2]
[53/55] Assessing channels#2217: Add missing newline in manage.py for black 26 comp...
  → Risk: 2 (low) [S=2 × P=1]
[54/55] Assessing channels#2202: Fix selenium test flakiness...
  → Risk: 6 (low) [S=3 × P=2]
[55/55] Assessing channels#2178: Update set_database_connection to fix #2176...
  → Risk: 12 (low) [S=4 × P=3]

✓ Completed 55 LLM-only assessments

In [15]:
# ── Display LLM-only results ─────────────────────────────────────────
rows = []
for r in llm_only_results:
    a = r["assessment"]
    if "error" not in a:
        rows.append({
            "PR": r["pr_id"],
            "title": r["pr_title"][:40],
            "severity": a["severity"],
            "probability": a["probability"],
            "risk_score": a["risk_score"],
            "risk_level": a["risk_level"],
        })

df_llm_only = pd.DataFrame(rows)
print("LLM-Only Risk Assessments:")
display(df_llm_only.sort_values("risk_score", ascending=False))

LLM-Only Risk Assessments:

,PR,title,severity,probability,risk_score,risk_level
12,wagtail#13930,Defer validation of required fields with,7,6,42,high
9,drf#9735,Preserve ordering in `MultipleChoiceFiel,7,6,42,high
10,wagtail#14017,Store preview data in a dedicated FormSt,7,6,42,high
11,wagtail#14034,Use the same UUID for autosave audit log,7,6,42,high
29,oscar#4551,[FEAT] Add code in address models,7,6,42,high
39,simplejwt#887,fix: always stringify user_id claim,7,6,42,high
3,django#20027,Fixed #20024 -- Fixed handling of __in l,7,5,35,medium
34,filter#1698,Removed deprecated schema generation met,7,5,35,medium
46,guardian#976,Issue966,7,5,35,medium
17,netbox#21815,Fixes #21498: Fix Exception when changin,7,5,35,medium
45,guardian#974,Fixed user and group inconsistency with,7,5,35,medium
19,netbox#21805,Fixes: #21696 - Upgrade to django-rq==4.,7,5,35,medium
13,wagtail#13975,Autosave UX improvements,6,5,30,medium
16,netbox#21816,Closes #21770: Enable including/excludin,6,5,30,medium
35,simplejwt#966,chore: bump python-jose,7,4,28,medium
14,wagtail#13974,Avoid creating a new editing session whe,6,4,24,medium
28,oscar#4552,[FEAT] Add code in product review,6,4,24,medium
22,saleor#19011,Turn off deferred for fulfillment events,6,4,24,medium
21,saleor#17979,Fix checkout.discount amount when overri,6,4,24,medium
1,django#21046,Fixed #37016 -- Avoided propagating inva,6,4,24,medium
2,django#20889,Fixed #36973 -- Made fields.E348 detect,6,4,24,medium
5,drf#9902,Fix partial form data updates involving,6,4,24,medium
6,drf#9929,Include `choices` param for non-editable,6,4,24,medium
41,drf_spectacular#1467,Add l18n handling for Decimal field #146,6,4,24,medium
49,celery_beat#1009,Fix cron-descriptor >= 2.0 compatibility,6,4,24,medium
48,guardian#962,Improve managers typing and reduce code,6,4,24,medium
43,drf_spectacular#1416,Fix memory leak,6,4,24,medium
27,oscar#4556,deps: compatibility with django-treebear,6,4,24,medium
33,filter#1691,Cast data to QueryDict in LinkWidget.ren,6,4,24,medium
24,saleor#17687,Add missing migrations and fix failing t,6,4,24,medium
23,saleor#19012,Turn off deferred for fulfillment events,6,4,24,medium
38,simplejwt#959,feat: add django 6.0 and python 3.14 sup,5,4,20,medium
42,drf_spectacular#1450,[django-filter] Add null_label if set in,5,4,20,medium
4,django#21035,Fixed #36949 -- Improved RelatedFieldWid,5,4,20,medium
25,oscar#4521,use get_extra_context for the confirmati,5,4,20,medium
20,saleor#17890,[3.20] Add support for Kosovo country,5,4,20,medium
8,drf#9928,Fix `HTMLFormRenderer` with empty `datet,6,3,18,medium
47,guardian#969,Fix possible IndexError when trying to b,5,3,15,low
18,netbox#21829,Fixes: #21535 - Fix filtering of object-,5,3,15,low
40,drf_spectacular#1469,Fix regression introduced in #1450,5,3,15,low
54,channels#2178,Update set_database_connection to fix #2,4,3,12,low
15,netbox#21837,Closes #21795: Improve humanize_speed fo,4,3,12,low
26,oscar#4558,[FEAT] Make email search more flexible,4,3,12,low
37,simplejwt#963,fix: use curve-matching EC keys for ES38,4,2,8,low
7,drf#9931,Prepare bug fix release 3.17.1,3,2,6,low
50,celery_beat#986,Allow pytest 9,3,2,6,low
30,filter#1270,Run tests against Python 3.9,3,2,6,low
53,channels#2202,Fix selenium test flakiness,3,2,6,low
51,celery_beat#999,django_celery_beat v2.9.0,3,2,6,low
31,filter#1706,Add reference anchors to filter types to,3,2,6,low
44,drf_spectacular#1465,Update linting packages and fix new issu,3,2,6,low
0,django#21050,Refs #36949 -- Removed hardcoded pks in,2,1,2,low
32,filter#1703,Replace hardcoded pks in tests,2,1,2,low
36,simplejwt#964,Add importlib to doc dependencies,2,1,2,low
52,channels#2217,Add missing newline in manage.py for bla,2,1,2,low

## 7. Save Results

Save PR data and LLM-only assessments for use in Notebook 05.

In [17]:
# ── Save all experiment data ─────────────────────────────────────────
experiment_data = {
    "config": {
        "prs_per_repo": PRS_PER_REPO,
        "openai_model": OPENAI_MODEL,
        "repos": list(REPO_MAP.keys()),
    },
    "prs": all_prs,
    "llm_only_results": llm_only_results,
}

output_path = OUTPUT_DIR / "04_pr_data_and_llm_baseline.json"
with open(output_path, "w") as f:
    json.dump(experiment_data, f, indent=2, default=str)

# Persist to Drive so NB05 can pick it up across runtime resets
DRIVE_EXPERIMENT = DRIVE_DIR / "experiment_outputs"
DRIVE_EXPERIMENT.mkdir(exist_ok=True)
shutil.copy2(output_path, DRIVE_EXPERIMENT / output_path.name)

print(f"  LLM-only assessments: {len(llm_only_results)}")

print(f"✓ Saved to {output_path} (+ Drive)")
print(f"  PRs: {len(all_prs)}")
print(f"  File size: {output_path.stat().st_size / 1024:.1f} KB")

  LLM-only assessments: 55
✓ Saved to /content/rgat_project/experiment_outputs/04_pr_data_and_llm_baseline.json (+ Drive)
  PRs: 55
  File size: 521.9 KB

In [20]:
# ── Also save a compact node list for Notebook 05 ────────────────────
# This avoids Notebook 05 needing to re-parse diffs
pr_nodes = []
for pr_data in all_prs:
    e = pr_data["entities"]
    all_node_ids = (
        [nid for nid, _ in e["matched_modules"]]
        + [nid for nid, _ in e["matched_classes"]]
        + [nid for nid, _ in e["matched_functions"]]
    )
    pr_nodes.append({
        "pr_id": f"{pr_data['repo_short']}#{pr_data['pr_number']}",
        "repo_short": pr_data["repo_short"],
        "pr_number": pr_data["pr_number"],
        "node_ids": all_node_ids,
    })

nodes_path = OUTPUT_DIR / "04_pr_node_mapping.json"
with open(nodes_path, "w") as f:
    json.dump(pr_nodes, f, indent=2)

# Persist to Drive
DRIVE_EXPERIMENT = DRIVE_DIR / "experiment_outputs"
DRIVE_EXPERIMENT.mkdir(exist_ok=True)

shutil.copy2(nodes_path, DRIVE_EXPERIMENT / nodes_path.name)

total_nodes = sum(len(p["node_ids"]) for p in pr_nodes)
print(f"✓ Node mapping saved to {nodes_path} (+ Drive)")
print(f"  {len(pr_nodes)} PRs, {total_nodes} total node references")

✓ Node mapping saved to /content/rgat_project/experiment_outputs/04_pr_node_mapping.json (+ Drive)
  55 PRs, 249 total node references

---

## Summary

This notebook collected real PRs from the Django ecosystem and established the **LLM-only baseline** risk assessments. The next step (Notebook 05) will:

1. Load the trained RGAT model
2. For each PR's matched nodes, extract k-hop subgraph context and attention weights
3. Re-prompt the LLM with **diff + structural context**
4. Compare LLM-only vs. LLM+RGAT assessments side by side

The saved files:
- `experiment_outputs/04_pr_data_and_llm_baseline.json` — Full PR data + LLM-only results
- `experiment_outputs/04_pr_node_mapping.json` — Compact node ID mapping for RGAT inference